export TREE_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export TABLE_EXTRACTION_HOME="$TREE_HOME/table-extraction/"
export PYTHONPATH="$PYTHONPATH:$TREE_HOME:$TABLE_EXTRACTION_HOME:$TABLE_EXTRACTION_HOME/pdf"
export DATAPATH="$TREE_HOME/data/paleo/documents/"
export MLPATH="$TREE_HOME/data/paleo/ml/"
